export const catalogueCopy = {
  no: {
    title: "Elbiler i Norge",
    intro:
      "Et lite utvalg med opplysninger fra norske produsentnettsider. Flere modeller kommer etter kildekontroll.",
    search: "Søk etter bil",
    brand: "Merke",
    all: "Alle merker",
    budget: "Makspris (NOK)",
    range: "Minste WLTP-rekkevidde (km)",
    sort: "Sorter",
    name: "Navn",
    price: "Laveste fra-pris",
    longest: "Lengste WLTP-rekkevidde",
    count: "biler",
    empty: "Ingen biler passer filtrene.",
    compare: "Sammenlign",
    choose: "Velg til sammenligning",
    details: "Se spesifikasjoner",
    clear: "Nullstill",
    selected: "valgt",
    limit: "Du kan sammenligne opptil fire biler.",
    photos: "Se originale bilder hos produsenten",
    missingPhoto: "Bilder kommer når bruksrett er avklart",
    checked: "Kilde kontrollert",
    sources: "Offisielle kilder",
    unknown: "Ikke dokumentert her",
    notice:
      "Begrenset katalog. Oppgitte tall er produsentopplysninger, ikke uavhengige tester. Bildeavtaler og enkelte spesifikasjoner gjenstår.",
    conditions:
      "WLTP er laboratoriemålt rekkevidde, ikke en vintertest. Temperatur, hjul og utstyr påvirker rekkevidde og lading. Priser kan endres; bekreft et skriftlig tilbud hos forhandler.",
    specifications: "Spesifikasjoner",
    back: "Alle biler",
    selectPrompt: "Velg biler fra katalogen for å sammenligne.",
    add: "Legg til biler",
    remove: "Fjern",
    incomplete: "Ingen publiserte biler er tilgjengelige akkurat nå.",
    from: "Fra",
    upto: "Opptil",
    unknownYear: "Modellår er ikke bekreftet for denne oppføringen.",
  },
  en: {
    title: "Electric cars in Norway",
    intro:
      "A small selection with information from Norwegian manufacturer websites. More models will follow after source checks.",
    search: "Search cars",
    brand: "Brand",
    all: "All brands",
    budget: "Maximum price (NOK)",
    range: "Minimum WLTP range (km)",
    sort: "Sort",
    name: "Name",
    price: "Lowest starting price",
    longest: "Longest WLTP range",
    count: "cars",
    empty: "No cars match these filters.",
    compare: "Compare",
    choose: "Select for comparison",
    details: "View specifications",
    clear: "Reset",
    selected: "selected",
    limit: "You can compare up to four cars.",
    photos: "See original photos at the manufacturer",
    missingPhoto: "Photos pending reuse permission",
    checked: "Source checked",
    sources: "Official sources",
    unknown: "Not documented here",
    notice:
      "Limited catalogue. Figures are manufacturer claims, not independent tests. Image permissions and some specifications are still outstanding.",
    conditions:
      "WLTP is laboratory range, not a winter test. Temperature, wheels and equipment affect range and charging. Prices may change; confirm a written dealer quote.",
    specifications: "Specifications",
    back: "All cars",
    selectPrompt: "Choose cars from the catalogue to compare.",
    add: "Add cars",
    remove: "Remove",
    incomplete: "No published cars are available right now.",
    from: "From",
    upto: "Up to",
    unknownYear: "Model year has not been confirmed for this entry.",
  },
};
