// Separate measurement bases prevent urban range or charger rating becoming WLTP/DC peak.
export const fieldUnits = {
  priceFromNok: "NOK",
  rangeWltpCombinedKm: "km",
  rangeWltpCityKm: "km",
  batteryCapacityKwh: "kWh",
  batteryUsableKwh: "kWh",
  batteryGrossKwh: "kWh",
  chargingAcKw: "kW",
  chargingDcPeakKw: "kW",
  charging10To80Minutes: "min",
  charging20To80Minutes: "min",
  charging30To80Minutes: "min",
  consumptionWltpKwhPer100Km: "kWh/100km",
  powerKw: "kW",
  powerPs: "PS",
  torqueNm: "Nm",
  acceleration0To100Seconds: "s",
  topSpeedKmh: "km/h",
  lengthMm: "mm",
  widthMm: "mm",
  heightMm: "mm",
  wheelbaseMm: "mm",
  groundClearanceMm: "mm",
  bootSeatsUpLitres: "L",
  bootSeatsDownLitres: "L",
  frunkLitres: "L",
  towingBrakedKg: "kg",
  towingUnbrakedKg: "kg",
  roofLoadKg: "kg",
  seats: "count",
  warrantyYears: "year",
  warrantyKm: "km",
  batteryWarrantyYears: "year",
  batteryWarrantyKm: "km",
  batteryWarrantyRetentionPercent: "%",
  modelYear: "year",
  drivetrain: "enum",
  heatPump: "boolean",
  batteryPreconditioning: "boolean",
  v2l: "boolean",
  connector: "enum",
} as const;

export type FactField = keyof typeof fieldUnits;
