import type { BrandSource } from "./types.js";

// A read page is discovery evidence, not verification of all models or order status.
export const sources: BrandSource[] = [
  {
    slug: "alfa-romeo",
    name: "Alfa Romeo",
    url: "https://www.alfaromeo.no/",
    status: "CONTENT_READ",
    notes: "Junior electric offer observed; exact trim brochure pending.",
  },
  {
    slug: "alpine",
    name: "Alpine",
    url: "https://www.alpinecars.no/biler",
    status: "CONTENT_READ",
    notes: "A290 and A390 offers observed.",
  },
  {
    slug: "audi",
    name: "Audi",
    url: "https://www.audi.no/no/bilmodeller/",
    status: "CONTENT_READ",
    notes:
      "A6 e-tron, Q4 e-tron, Q6 e-tron and e-tron GT families; concepts and combustion models excluded from discovery.",
  },
  {
    slug: "bmw",
    name: "BMW",
    url: "https://www.bmw.no/no/elbil.html",
    status: "CONTENT_READ",
    notes:
      "Electric catalogue and variant WLTP footnotes read; some new-model figures preliminary.",
  },
  {
    slug: "byd",
    name: "BYD",
    url: "https://byd.no/",
    status: "CONTENT_READ",
    notes:
      "Norwegian importer catalogue and Sealion 7 specifications read; confirm exact variants and price lists.",
  },
  {
    slug: "changan",
    name: "Changan / Deepal",
    url: "https://www.changaneurope.com/no/",
    status: "CONTENT_READ",
    notes: "Deepal S05 and S07 observed.",
  },
  {
    slug: "citroen",
    name: "Citroen",
    url: "https://www.citroen.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; full model and variant extraction pending.",
  },
  {
    slug: "cupra",
    name: "Cupra",
    url: "https://www.cupraofficial.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; full model and variant extraction pending.",
  },
  {
    slug: "dongfeng",
    name: "Dongfeng",
    url: "https://www.dong-feng.no/",
    status: "CONTENT_READ",
    notes: "BOX and VIGO observed; VIGO displays conflicting starting prices.",
  },
  {
    slug: "ds",
    name: "DS Automobiles",
    url: "https://www.dsautomobiles.no/",
    status: "CONTENT_READ",
    notes: "DS3 E-TENSE observed; dated tax copy requires current price-list confirmation.",
  },
  {
    slug: "fiat",
    name: "Fiat",
    url: "https://www.fiat.no/",
    status: "CONTENT_READ",
    notes: "Grande Panda electric, 600e and 500e observed; separate passenger and commercial vans.",
  },
  {
    slug: "firefly",
    name: "firefly",
    url: "https://www.firefly.world/no_NO",
    status: "CONTENT_READ",
    notes: "Norwegian product site; detailed specs pending.",
  },
  {
    slug: "ford",
    name: "Ford",
    url: "https://www.ford.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; full model and variant extraction pending.",
  },
  {
    slug: "gwm",
    name: "GWM / ORA",
    url: "https://www.gwm-global.com/brands.html",
    status: "NORWAY_UNCONFIRMED",
    notes:
      "Norway in global territory list does not verify local offers. gwm.no is an unrelated investment company. Do not use Swedish prices/specs.",
  },
  {
    slug: "honda",
    name: "Honda",
    url: "https://www.honda.no/cars.html",
    status: "CONTENT_READ",
    notes: "e:Ny1 offer observed; exclude hybrid range.",
  },
  {
    slug: "hongqi",
    name: "Hongqi",
    url: "https://hongqi.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; full model and variant extraction pending.",
  },
  {
    slug: "hyundai",
    name: "Hyundai",
    url: "https://www.hyundai.com/no/no",
    status: "CONTENT_READ",
    notes: "WLTP footnotes read; IONIQ 3 figures explicitly preliminary.",
  },
  {
    slug: "jac",
    name: "JAC",
    url: "https://jacmotors.no/modeller/e30x",
    status: "CONTENT_READ",
    notes:
      "E30X variant table read; battery, dimensions and weights contain conflicts. Brochure cross-check required.",
  },
  {
    slug: "jeep",
    name: "Jeep",
    url: "https://www.jeep.com/no/",
    status: "CONTENT_READ",
    notes: "Norwegian homepage retrieved; exact BEV variants pending.",
  },
  {
    slug: "kgm",
    name: "KGM",
    url: "https://kgm-auto.no/modeller/torres-evx",
    status: "CONTENT_READ",
    notes:
      "Torres EVX specifications and linked Norwegian price PDF inspected; boot/payload conflicts flagged.",
  },
  {
    slug: "kia",
    name: "Kia",
    url: "https://www.kia.no/",
    status: "CONTENT_READ",
    notes:
      "Current importer lists EV2/3/4/5/6/9 and passenger PV5. EV9 details read; kia.com/no content was less current.",
  },
  {
    slug: "lexus",
    name: "Lexus",
    url: "https://www.lexus.no/",
    status: "CONTENT_READ",
    notes:
      "RZ500e AWD Luxury offer observed; expiry and price basis pending. ES/TZ require powertrain and availability checks.",
  },
  {
    slug: "lotus",
    name: "Lotus",
    url: "https://www.lotuscars.com/nb-NO",
    status: "CONTENT_READ",
    notes: "Eletre BEV and Emeya starting prices. Exclude hybrid Eletre X.",
  },
  {
    slug: "lucid",
    name: "Lucid",
    url: "https://lucidmotors.com/nb-no",
    status: "CONTENT_READ",
    notes: "Air named-variant prices observed; Gravity details pending.",
  },
  {
    slug: "maserati",
    name: "Maserati",
    url: "https://www.maserati.com/no/no/models",
    status: "EXTRACTION_BLOCKED",
    notes: "Official page fetch failed; no specifications accepted.",
  },
  {
    slug: "maxus",
    name: "Maxus",
    url: "https://maxus.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; distinguish passenger MPVs from commercial-only vehicles.",
  },
  {
    slug: "mazda",
    name: "Mazda",
    url: "https://www.mazda.no/modeller/",
    status: "EXTRACTION_BLOCKED",
    notes: "Page returned no extractable content; no specifications accepted.",
  },
  {
    slug: "mercedes-benz",
    name: "Mercedes-Benz",
    url: "https://www.mercedes-benz.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved after model page failed; detailed model extraction pending.",
  },
  {
    slug: "mg",
    name: "MG",
    url: "https://www.mgmotor.eu/nn-NO/",
    status: "CONTENT_READ",
    notes:
      "MG4, MGS5 EV, MGS6 EV, IM5, IM6 and Cyberster observed; use the actual nn-NO site locale.",
  },
  {
    slug: "mini",
    name: "MINI",
    url: "https://www.mini.no/no_NO/home.html",
    status: "CONTENT_READ",
    notes: "Electric Cooper, Aceman and Countryman; keep combustion siblings separate.",
  },
  {
    slug: "mitsubishi",
    name: "Mitsubishi",
    url: "https://www.mitsubishi-motors.no/",
    status: "CONTENT_READ",
    notes: "Eclipse Cross EV observed; do not confuse with older PHEV or Outlander PHEV.",
  },
  {
    slug: "nio",
    name: "NIO",
    url: "https://www.nio.com/no_NO",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; battery ownership versus subscription pricing must be separated.",
  },
  {
    slug: "nissan",
    name: "Nissan",
    url: "https://www.nissan.no/",
    status: "CONTENT_READ",
    notes:
      "New LEAF and MICRA starting prices and maximum ranges; ARIYA also listed. Do not mix old/new generations.",
  },
  {
    slug: "opel",
    name: "Opel",
    url: "https://www.opel.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; full model and variant extraction pending.",
  },
  {
    slug: "peugeot",
    name: "Peugeot",
    url: "https://www.peugeot.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; full model and variant extraction pending.",
  },
  {
    slug: "polestar",
    name: "Polestar",
    url: "https://www.polestar.com/no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; exact model-year, variant and option package verification pending.",
  },
  {
    slug: "porsche",
    name: "Porsche",
    url: "https://www.porsche.com/norway/no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; exact Taycan, Macan and other BEV configurations pending.",
  },
  {
    slug: "renault",
    name: "Renault",
    url: "https://www.renault.no/",
    status: "CONTENT_READ",
    notes:
      "Renault 4 order page observed; new Megane announced for 2027. Manufacturer says some backgrounds are AI-edited; photos need visual review.",
  },
  {
    slug: "seres",
    name: "Seres",
    url: "https://seresnorge.no/",
    status: "CONTENT_READ",
    notes: "Seres 5 dimensions observed; current variant detail page pending.",
  },
  {
    slug: "skoda",
    name: "Skoda",
    url: "https://www.skoda-auto.no/elbiler",
    status: "CONTENT_READ",
    notes:
      "Enyaq, Enyaq Coupe, Elroq, Epiq and Peaq described; exact order status and brochures pending.",
  },
  {
    slug: "smart",
    name: "smart",
    url: "https://www.smart.no/modeller/5",
    status: "CONTENT_READ",
    notes: "#1, #3, #5 navigation; #5 AWD, heat pump and charging details observed.",
  },
  {
    slug: "subaru",
    name: "Subaru",
    url: "https://www.subaru.no/",
    status: "CONTENT_READ",
    notes:
      "Solterra, Uncharted, E-Outback; 10-year cover is service-activated, not unconditional new-car warranty.",
  },
  {
    slug: "suzuki",
    name: "Suzuki",
    url: "https://suzuki.no/modeller/evitara",
    status: "CONTENT_READ",
    notes:
      "e VITARA 4x4 table read; ambiguous consumption/AC units and conflicting displayed prices withheld.",
  },
  {
    slug: "tesla",
    name: "Tesla",
    url: "https://www.tesla.com/no_NO/support/vehicle-warranty",
    status: "CONTENT_READ",
    notes:
      "Norwegian warranty table read. Model Y product page extraction still blocked/incomplete; battery capacity, pricing and current configurator specifications not obtained.",
  },
  {
    slug: "toyota",
    name: "Toyota",
    url: "https://www.toyota.no/nybil",
    status: "CONTENT_READ",
    notes: "Model index retrieved; full BEV-only variant extraction pending.",
  },
  {
    slug: "volkswagen",
    name: "Volkswagen",
    url: "https://www.volkswagen.no/no/alle-bilmodeller.html",
    status: "CONTENT_READ",
    notes:
      "Norwegian starting prices observed; concepts and commercial-only vehicles excluded. New-model delivery status still requires review.",
  },
  {
    slug: "volvo",
    name: "Volvo",
    url: "https://www.volvocars.com/no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved after /cars page failed; detailed BEV extraction pending.",
  },
  {
    slug: "voyah",
    name: "Voyah",
    url: "https://www.voyah.no/",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; BEV versus range-extender and passenger variants require review.",
  },
  {
    slug: "xpeng",
    name: "XPENG",
    url: "https://www.xpeng.com/no",
    status: "CONTENT_READ",
    notes: "Homepage retrieved; detailed configuration and delivery status pending.",
  },
  {
    slug: "zeekr",
    name: "Zeekr",
    url: "https://www.zeekr.eu/nb-no",
    status: "CONTENT_READ",
    notes:
      "001, X, 7X and 7GT BEV figures observed. Do not infer BEV status for 9X from this page.",
  },
];
